export const navigationMenu = [
    {
        "title": "Main",
        "pageName": "Dashboard",
        "icon": "home",
        "path": "/index",
    },
    {
        "title": "Entry",
        "pageName": "Daily Entry",
        "icon": "users",
        "path": "/daily-entry",
    },
    {
        "title": "Employee",
        "pageName": "Employee",
        "icon": "users",
        "path": "/employee",
    },
    {
        "title": "",
        "pageName": "Center",
        "icon": "users",
        "path": "/center",
    },
    {
        "title": "",
        "pageName": "Payment Mode",
        "icon": "users",
        "path": "/payment-mode",
    },
    {
        "title": "",
        "pageName": "Expensive",
        "icon": "users",
        "path": "/expensive",
    },
    {
        "title": "",
        "pageName": "Feed Entry",
        "icon": "users",
        "path": "/feed-entry",
    },
    {
        "title": "",
        "pageName": "Shift",
        "icon": "users",
        "path": "/shift",
    },
    {
        "title": "",
        "pageName": "Supplier",
        "icon": "users",
        "path": "/supplier",
    },
    {
        "title": "",
        "pageName": "Purchase",
        "icon": "users",
        "path": "/purchase",
    },
    {
        "title": "",
        "pageName": "Advance",
        "icon": "users",
        "path": "/advance",
    },
    {
        "title": "Customers",
        "pageName": "Customers",
        "icon": "users",
        "path": "/customer",
    },
    {
        "title": "Report",
        "pageName": "Sales Quotation",
        "icon": "users",
        "path": "/sales-report",
    },
    {
        "title": "",
        "pageName": "Confirm Quotation",
        "icon": "users",
        "path": "/confirm-report",
    },
    {
        "title": "",
        "pageName": "Cancel Quotation",
        "icon": "users",
        "path": "/cancel-report",
    },
    {
        "title": "Master",
        "pageName": "Product",
        "icon": "users",
        "path": "/product",
    },
    {
        "title": "",
        "pageName": "Role",
        "icon": "users",
        "path": "/role",
    },
    {
        "title": "",
        "pageName": "Customer Category",
        "icon": "shopping-cart",
        "path": "/customer-category",
    },
    {
        "title": "",
        "pageName": "Color",
        "icon": "users",
        "path": "/color",
    },
    {
        "title": "",
        "pageName": "Product Unit",
        "icon": "users",
        "path": "/product-unit",
    },
    {
        "title": "",
        "pageName": "Quotation Status",
        "icon": "users",
        "path": "/quotation-status",
    },
]